# Generated by Django 2.1.3 on 2018-11-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliesOn', models.CharField(choices=[('Signal', 'Signal'), ('Value', 'Value'), ('valueType', 'valueType')], default=None, max_length=50)),
                ('ruleType', models.CharField(choices=[('Should Be', 'Should Be'), ('Should Not', 'Should Not')], default='Should Be', max_length=50)),
                ('operator', models.CharField(choices=[('equal to', 'equal to'), ('less than', 'less than'), ('greater than', 'greater than')], default=None, max_length=50)),
                ('value', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SignalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('valueType', models.CharField(blank=True, max_length=50, null=True)),
                ('isViolated', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
