# Generated by Django 2.1.3 on 2018-11-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='valueType',
            field=models.CharField(choices=[('Integer', 'Integer'), ('String', 'String'), ('Datetime', 'Datetime')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='rule',
            name='appliesOn',
            field=models.CharField(choices=[('ATL1', 'ATL1'), ('ATL10', 'ATL10'), ('ATL2', 'ATL2'), ('ATL3', 'ATL3'), ('ATL4', 'ATL4'), ('ATL5', 'ATL5'), ('ATL6', 'ATL6'), ('ATL7', 'ATL7'), ('ATL8', 'ATL8'), ('ATL9', 'ATL9')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(default=None, help_text="If using date, please use the following format 'DD-Mon-YYYY HH24:MI:SS'", max_length=100),
        ),
    ]
