# Generated by Django 2.1.3 on 2018-11-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181111_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('=', 'equal to'), ('<', 'less than'), ('>', 'greater than')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='ruleType',
            field=models.CharField(choices=[('Should Be', 'Should Be'), ('Should Not Be', 'Should Not Be')], default='Should Be', max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='value',
            field=models.CharField(default=None, help_text="If using date, please use the following format 'YYYY-MM-DD HH24:MI:SS'", max_length=100),
        ),
    ]
